In [1]:
import cv2
import matplotlib.pyplot as plt
import numpy as np
import os
import math
import seaborn as sns
from scipy import signal
from matplotlib.colors import LogNorm, Normalize

In [2]:
a = np.expand_dims(np.array([-1,0,1]), axis=1)
b = np.expand_dims(np.array([3,10,3]), axis=1)

In [4]:
H_x_sobel_imp = b@a.T
print("Sobel Improved Edge Detector for x-axis (Not multiplied by 1/32 yet)")
print(H_x_sobel_imp)
H_y_sobel_imp = a@b.T
print("Sobel Improved Edge Detector for y-axis (Not multiplied by 1/32 yet)")
print(H_y_sobel_imp)

Sobel Improved Edge Detector for x-axis (Not multiplied by 1/32 yet)
[[ -3   0   3]
 [-10   0  10]
 [ -3   0   3]]
Sobel Improved Edge Detector for y-axis (Not multiplied by 1/32 yet)
[[ -3 -10  -3]
 [  0   0   0]
 [  3  10   3]]
